services:
  # O Servidor Web (Nginx)
  app_nginx:
    image: nginx:alpine
    container_name: pos-nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pos-backend
  
  # O Servidor MySQL
  pos-mysql:
    image: mysql:8.4
    container_name: pos-mysql
    ports: 
      - "3306:3306" # Se esta porta estiver ocupada, use 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-8.4:/var/lib/mysql
    restart: always
    healthcheck: # <--- 1. Healthcheck adicionado
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s

  # Serviço phpMyAdmin (Interface de Gerenciamento do Banco de Dados)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pos-phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: pos-mysql 
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # phpMyAdmin só precisa de 'depends_on' simples, mas usa o Healthcheck se definido
    depends_on:
      - pos-mysql
    restart: always  
  
  # O Serviço de Processamento PHP (FPM)
  pos-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nissibi/pos-backend:1.0
    container_name: pos-backend
    volumes:
      - .:/var/www/html
    # 2. Depends_on avançado para garantir que o MySQL esteja pronto
    depends_on:
      pos-mysql:
        condition: service_healthy

volumes:
  mysql-8.4: