
services:
  # O Servidor Web (Nginx)
  app_nginx:
    image: nginx:alpine
    container_name: xicompra_nginx
    # Mapeia a porta 80 do container para a porta 8080 da sua máquina
    ports:
      - "8080:80"
    volumes:
      # Mapeia o código da aplicação (para que as mudanças sejam refletidas)
      - .:/var/www/html
      # Mapeia o arquivo de configuração do Nginx (próxima etapa)
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pos-backend

  # O Serviço de Processamento PHP (FPM)
  pos-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pos-backend:1.0
    container_name: pos-backend
    volumes:
      # Mapeia o código da aplicação (IMPORTANTE para que as mudanças funcionem)
      - .:/var/www/html